### ISSUE TITLE
Why not use "bottr" for CLI

### ISSUE THREAD

**Issue by vutran** [Bottr-js/Bottr#21]
For `bottr-cli`, it would be better to just use `bottr`.  I know I can simply create an alias as a user, but it is a lot easier to type. Thoughts on why `bottr-cli` was chosen instead as the primary command?

**Comment by ummahusla** [comment]
That's a good point. But the thing is that at the moment we have several repositories like `Bottr`, `Botrr-CLI`, `Bottr-App` and so on, and in order not to confuse people, I would personally leave it as it is. 

@jcampbell05 What do you think?

**Comment by jcampbell05** [comment]
So you mean to call the actual binary NPM creates `bottr`rather than the Repo or package.

Historically this was called `bottr-cli` as it was supposed to let you test your bot via the cli. However it doesn't really do this now (only make a new project and start up your bot) but one could argue the name is still valid.

This tool was inspired very much the way react-native does things and I've noticed that they don't have `cli` for their binary (not the package though). I've looked at other tools like Heroku and they also don't do this.

If we did so this.

The main hurdle we will have to overcome is an upgrade path for those on `bottr-cli` I think the best is to maybe offer a binary named `bottr` in the package.json for `Bottr-CLI` so you can use either `bottr` or `bottr-cli`.

**Comment by vutran** [comment]
Closing this as it is has recently been merged in.
