### ISSUE TITLE
Why callbacks?

### ISSUE THREAD

**Issue by gunar** [Bottr-js/Bottr#69]
and not Promises?

Would love to hear your reasoning. Thank you!

**Comment by jcampbell05** [comment]
@gunar Methods like hears and on are event based so make sense to use callbacks since promises are for a different design pattern and don't work with those.

Although maybe they could work ? I don't know.

However,  I would love to add in a way of adding some promises for some of the actions the bot can perform such as sending a message. So you could use `.then` to do something after a message was sent or a request finished :)

**Comment by gunar** [comment]
Yup, `hear` is event-based so that needs to take a callback/thunk. But from then on one could use promises to chain a sequence of methods (e.g. `say.then(ask).then(say)`). Thank you!

**Comment by jcampbell05** [comment]
@gunar  Yup makes total sense and something I would love to have 👍
